#    SPDX-FileCopyrightText: 2021 Monaco F. J. <monaco@usp.br>
#    SPDX-FileCopyrightText: 2025 Arthur Vergaças <arthurvdm@gmail.com>
#
#    SPDX-License-Identifier: GPL-3.0-or-later
#
#  This file is a derivative of SYSeg (https://gitlab.com/monaco/syseg)
#  and includes modifications made by the following author(s):
#  Arthur Vergaças <arthurvdm@gmail.com>

CC=gcc
MAKE=make

include build.mk

# SYSeg's  convenience rules (not related to the example itself)
include bintools.mk
